# Gunakan image dasar nginx
FROM nginx:latest

# Salin file HTML ke direktori default Nginx
COPY ./html /usr/share/nginx/html

# Salin file CSS ke direktori default Nginx
COPY ./css /usr/share/nginx/html/css

